language: R
cache: packages

matrix:
  include:
    - r: oldrel
    - r: release
      before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - r: devel
    - os: osx
      fortran: false
      latex: false

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libfreetype6
      - libmagick++-dev

# work around temporary travis + R 3.5 bug
r_packages:
  - devtools
  - caret
  - randomForest
  - e1071

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
