# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate permutations of a vector of indexes.
#'
#' @param original_document Index of words in a text document.
#' @param number_permutations number of permutation to generate.
#' @return a list of permutations. The permutation sizes are not all the same.
get_index_permutations <- function(original_document, number_permutations) {
    .Call('lime_get_index_permutations', PACKAGE = 'lime', original_document, number_permutations)
}

